<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:18:08.
 */
class Patients_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Patients_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Patients_model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Patients_model::getpatientlistDb
     * @todo   Implement testGetpatientlistDb().
     */
    public function testGetpatientlistDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients_model::addPatient
     * @todo   Implement testAddPatient().
     */
    public function testAddPatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients_model::delPatient
     * @todo   Implement testDelPatient().
     */
    public function testDelPatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients_model::updatePatient
     * @todo   Implement testUpdatePatient().
     */
    public function testUpdatePatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients_model::selectPatient
     * @todo   Implement testSelectPatient().
     */
    public function testSelectPatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
