<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:17:58.
 */

include_once '../application/models/Patientreports_model.php';
class Patientreports_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Patientreports_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Patientreports_model();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Patientreports_model::getreportlist
     * @todo   Implement testGetreportlist().
     */
    public function testGetreportlist() {

    }

    /**
     * @covers Patientreports_model::getreportdetail
     * @todo   Implement testGetreportdetail().
     */
    public function testGetreportdetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports_model::setpdffilename
     * @todo   Implement testSetpdffilename().
     */
    public function testSetpdffilename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports_model::getpdfinfo
     * @todo   Implement testGetpdfinfo().
     */
    public function testGetpdfinfo() {
        // $this->assertEquals(false,$this->object->getpdfinfo(4));
    }

}
