<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:18:08.
 */
class Reports_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Reports_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Reports_model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Reports_model::getreportlistDb
     * @todo   Implement testGetreportlistDb().
     */
    public function testGetreportlistDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::getreportdetaillistDb
     * @todo   Implement testGetreportdetaillistDb().
     */
    public function testGetreportdetaillistDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::getpatientlist
     * @todo   Implement testGetpatientlist().
     */
    public function testGetpatientlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::patientcodecheck
     * @todo   Implement testPatientcodecheck().
     */
    public function testPatientcodecheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::addReport
     * @todo   Implement testAddReport().
     */
    public function testAddReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::delReport
     * @todo   Implement testDelReport().
     */
    public function testDelReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::updateReport
     * @todo   Implement testUpdateReport().
     */
    public function testUpdateReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::selectReport
     * @todo   Implement testSelectReport().
     */
    public function testSelectReport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::addReportDetail
     * @todo   Implement testAddReportDetail().
     */
    public function testAddReportDetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::delReportDetail
     * @todo   Implement testDelReportDetail().
     */
    public function testDelReportDetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::updateReportDetail
     * @todo   Implement testUpdateReportDetail().
     */
    public function testUpdateReportDetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Reports_model::selectReportDetail
     * @todo   Implement testSelectReportDetail().
     */
    public function testSelectReportDetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
