<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:18:08.
 */
class Users_modelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Users_model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Users_model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Users_model::checkuser
     * @todo   Implement testCheckuser().
     */
    public function testCheckuser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::checkpatient
     * @todo   Implement testCheckpatient().
     */
    public function testCheckpatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::getuserlistDb
     * @todo   Implement testGetuserlistDb().
     */
    public function testGetuserlistDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::addUser
     * @todo   Implement testAddUser().
     */
    public function testAddUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::delUser
     * @todo   Implement testDelUser().
     */
    public function testDelUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::updateUser
     * @todo   Implement testUpdateUser().
     */
    public function testUpdateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::selectUser
     * @todo   Implement testSelectUser().
     */
    public function testSelectUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::validatePatient
     * @todo   Implement testValidatePatient().
     */
    public function testValidatePatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::getPatientDetails
     * @todo   Implement testGetPatientDetails().
     */
    public function testGetPatientDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::get_db_session_data
     * @todo   Implement testGet_db_session_data().
     */
    public function testGet_db_session_data() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users_model::create_member
     * @todo   Implement testCreate_member().
     */
    public function testCreate_member() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
