<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-03 at 17:09:35.
 */

define("APPPATH", "../application/");
require_once '../application/libraries/SendMail.php';

class SendMailTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SendMail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
         $options = array(
            'SMTP_HOST' => "smtp.live.com",
            'SMTP_PORT' => 587,
            'SMTP_USER' => "ucak_hasan@hotmail.com",
            'SMTP_PASS' => "1231",
            'SMTP_FROM' => "",
            'SMTP_FROM_NAME' => "hucak"
        );
        $this->object = new SendMail($options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SendMail::sendtomail
     * @todo   Implement testSendtomail().
     */
    public function testSendtomail() {

        $this->assertEquals(false,$this->object->sendtomail("", "", "", ""));
        $this->assertEquals(false,$this->object->sendtomail("abc", "terer", "sdfasdfsadf", ""));
      //  $this->assertEquals(false,$this->object->sendtomail("", "", "", ""));
        $this->assertEquals(true,$this->object->sendtomail("hasan.ucak@gmail.com", "Test", "bodyyy", ""));
    }

}
