<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:16:14.
 */
class LabreportsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Labreports
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Labreports;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Labreports::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::reportlist
     * @todo   Implement testReportlist().
     */
    public function testReportlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::getreportdetailList
     * @todo   Implement testGetreportdetailList().
     */
    public function testGetreportdetailList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::getreportList
     * @todo   Implement testGetreportList().
     */
    public function testGetreportList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::psearch
     * @todo   Implement testPsearch().
     */
    public function testPsearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::reportsendpatient
     * @todo   Implement testReportsendpatient().
     */
    public function testReportsendpatient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::reportcrud
     * @todo   Implement testReportcrud().
     */
    public function testReportcrud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Labreports::reportdetailcrud
     * @todo   Implement testReportdetailcrud().
     */
    public function testReportdetailcrud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
