<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:16:14.
 */
class PatientreportsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Patientreports
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Patientreports;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Patientreports::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::patientlist
     * @todo   Implement testPatientlist().
     */
    public function testPatientlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::getReportList
     * @todo   Implement testGetReportList().
     */
    public function testGetReportList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::getReportDetail
     * @todo   Implement testGetReportDetail().
     */
    public function testGetReportDetail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::converttopdf
     * @todo   Implement testConverttopdf().
     */
    public function testConverttopdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::senttopdf
     * @todo   Implement testSenttopdf().
     */
    public function testSenttopdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patientreports::displaypdf
     * @todo   Implement testDisplaypdf().
     */
    public function testDisplaypdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
