<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:16:15.
 */
class PatientsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Patients
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Patients;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Patients::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients::patientlist
     * @todo   Implement testPatientlist().
     */
    public function testPatientlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients::getpatientList
     * @todo   Implement testGetpatientList().
     */
    public function testGetpatientList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Patients::patientcrud
     * @todo   Implement testPatientcrud().
     */
    public function testPatientcrud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
