<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:16:15.
 */
class TestsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Tests
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tests;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Tests::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tests::testlist
     * @todo   Implement testTestlist().
     */
    public function testTestlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tests::getTestTList
     * @todo   Implement testGetTestTList().
     */
    public function testGetTestTList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Tests::testTcrud
     * @todo   Implement testTestTcrud().
     */
    public function testTestTcrud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
