<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-04 at 00:16:14.
 */
class UsersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Users
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Users;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Users::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::plogin
     * @todo   Implement testPlogin().
     */
    public function testPlogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::alogin
     * @todo   Implement testAlogin().
     */
    public function testAlogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::userproc
     * @todo   Implement testUserproc().
     */
    public function testUserproc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::userlist
     * @todo   Implement testUserlist().
     */
    public function testUserlist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::getuserList
     * @todo   Implement testGetuserList().
     */
    public function testGetuserList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::usercrud
     * @todo   Implement testUsercrud().
     */
    public function testUsercrud() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Users::aloginProc
     * @todo   Implement testAloginProc().
     */
    public function testAloginProc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
